# 1. Variables and Arithmetic

In this first section, we learn some basics on variables in Python. In particular, we
learn how to 
* assign and print out variables,
* convert them from one type to another,
* perform (standard) calculations, and 
* use logical operators.

Keywords: ```type```, ```=```, ```print```, ```int```, ```float```, ```str```, ```bool```, 
```==```, ```<=```, ```is```, ```and```, ```or```

***
## Initialise and print variables

The two most commonly used number data types are **integers**, i.e. whole numbers, like

In [1]:
type(1)

int

and **floating-point numbers** or **floats**, i.e. decimal numbers, like

In [2]:
type(2.5)

float

Another important data type are strings which are used to represent text

In [3]:
type("like this text.")

str

For assigning values to variables, the ```=``` operator is used

In [4]:
integer_variable = 10
float_variable = 2.5
complex_variable = 1 + 2j
string_variable = "some text"
another_string_variable = 'this is also a string'

In [5]:
integer_variable

10

In [6]:
print(integer_variable)

10


#### Note 
the difference between using ```integer_variable``` in the cell above and ```print(integer_variable)```. In the first case,
Jupyter Notebooks allow us to inspect the internal value of the variable as it would be used in the program
(note the ```[5]:``` indiciating the last output of this particular cell). In the second case, ```print```
is what you would require if you want to output something during the execution of the program. 

In [7]:
type(integer_variable)

int

In [8]:
print(float_variable)

2.5


In [9]:
type(float_variable)

float

In [10]:
string_variable

'some text'

In [11]:
print(another_string_variable)

this is also a string


In [12]:
complex_variable

(1+2j)

In [13]:
a = 127
print(a)

127


In [14]:
a = 1.1
print(a)

1.1


***
## Converting variables between different data types

Frequently, we start working with variables which are of a particular type 
but notice half way through that we actually require another type. Type 
conversion is not a problem in Python. In fact, we change the type on the fly.

In [15]:
new_int = 4

print( "Initially, we had new_int =", new_int, "of type", type(new_int) )

new_int = float(new_int)

print("Now, we have new_int =", new_int, "of type", type(new_int))

Initially, we had new_int = 4 of type <class 'int'>
Now, we have new_int = 4.0 of type <class 'float'>


#### Note 
that in this example ```<class '...'>``` has something to do with the data type.
You don't need to pay too much attention to this for the time being.

In [16]:
int(2.7)

2

In [17]:
int('15')

15

In [18]:
float('5.7')

5.7

In [19]:
converted_int = str(integer_variable)

print("The converted integer is of type", type(converted_int))
converted_int

The converted integer is of type <class 'str'>


'10'

***
## Arithmetic operators

Using arithmetic operations (```+```, ```-```, ```/```, ```*```, ```//```, ```**```, ```%```) should exactly work as you would expect it. 

In [22]:
10 + 2

12

In [23]:
integer_variable + float_variable

12.5

In [24]:
'example' + 3

TypeError: can only concatenate str (not "int") to str

In [25]:
'example' + str(3)

'example3'

In [26]:
100 - 1

99

In [27]:
100 - (-1)

101

In [28]:
integer_variable - float_variable

7.5

In [29]:
100 * -2

-200

In [30]:
11/2

5.5

In [31]:
11//2

5

In [32]:
int(11/2)

5

#### Note
that the **integer division** (```//```) operation ```11//2``` and ```int(11/2)``` both give you the same result which is the integer
before the decimal point, i.e. decimals are clipped away.

On the other hand, the **modulus** operator ```%``` returns the remainder of a division. For example:

In [33]:
11%2

1

In [34]:
print("2 divides 11 =>", 11//2, "times with a remainder of =>", 11%2)

2 divides 11 => 5 times with a remainder of => 1


In [35]:
1 / 0

ZeroDivisionError: division by zero

For exponentiation in Python we can use the ```**``` operator or ```pow``` function. So, for $2^3$ we do

In [36]:
2**3

8

or

In [37]:
pow(2,3)

8

In [38]:
9**0.5

3.0

***
## Logical operators & more

Boolean variables represent another important data type which only allow two values, ```True``` and ```False```.

In [39]:
bool(1)

True

In [40]:
bool(0)

False

In [41]:
bool(100)

True

In [42]:
bool(0.5)

True

In [43]:
bool(1) == True

True

In [45]:
bool(0.5) == False

False

In [46]:
1 == True

True

In [47]:
0 == False

True

#### Note
that (in most programming languages) the mathematical symbol for *equals* 
is redefined as the ```==``` operator. This is necessary because ```=``` is already 
used for assigning values to variables. 

In [48]:
bool_variable = True
placeholder = None

In [49]:
placeholder is None # this is the same: placeholder == None

True

In [50]:
bool_variable = True

not bool_variable

False

In [51]:
5 == 5.0

True

In [52]:
int(5) == float(5)

True

In [53]:
10 != 10.0

False

In [54]:
10 <= 10

True

In [55]:
10 >= 11

False

In [56]:
"a" > "b"

False

#### Note 
that strings are ordered lexicographically. 

In [57]:
'car' < 'cat'

True

Suppose you are looking for new flat and you find an offer located in Basel which 
has a monthly rent of 500 CHF. 

In [58]:
rent = 500
city = 'Basel'

Consider three scenarios: In the first, you want to pay less than 700 CHF and live in Basel. 
Is this a relevant offer for you?

In [59]:
rent < 700 and city == 'Basel'

True

In the second scenario, you would like to pay less than 700 CHF or live in Zurich.
Would you be interested?

In [60]:
rent < 700 or city == 'Zurich'

True

In the last scenario, you would like to pay less than 400 CHF or live in Zurich. 
What about now?

In [61]:
rent < 400 or city == 'Zurich'

False

***
## Some caveats

In [62]:
0.1*3

0.30000000000000004

This is because the binary representation of 0.1 is a periodically repeating number, i.e.

$$ 0.1_\text{decimal} \ \hat{=} \ 0.0\overline{0011}_\text{binary}.$$

The representation of this number needs to be clipped at some point, as we have a limited
memory resources to represent numbers.

In [63]:
5/11

0.45454545454545453

In [64]:
2e400

inf

You have a lot of freedom in deciding the name of your variable.
You can use underscores (*_*), numbers, or capital letters like

In [65]:
integer2 = 15
integer_variable = 10
integerVariable = 5

However, the following would not work, as they are **illegal variable names**:

In [66]:
2integer = 15

<>:1: SyntaxWarning: invalid decimal literal
<>:1: SyntaxWarning: invalid decimal literal
/var/folders/y_/2qg_gjq937z8c0xctbn85x8r0000gn/T/ipykernel_72556/2442139553.py:1: SyntaxWarning: invalid decimal literal
  2integer = 15


SyntaxError: invalid syntax (2442139553.py, line 1)

In [67]:
integer-variable = 10

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (1651779667.py, line 1)

In [68]:
integer variable = 5

SyntaxError: invalid syntax (3333453504.py, line 1)

***
## Exercise section

(1.) Assign to two different variables the values ```123``` and ```123.0```.

In [69]:
a = 123
b = 123.0

(2.) Check with ```==``` whether these two variables are equal and save the result
to a new variable.

In [75]:
equal = a == b

True

(3.) Print the following sentences using strings, the two variables from (1.) and 
the boolean (result) variable from (2.) to output the following sentences:

``` Comparing the two variables leads to the result: 123 == 123.0 is True```

In [76]:
"Comparing the two variables leads to the result: " + str(a) + " == " + str(b) + " is " + str(equal)

'Comparing the two variables leads to the result: 123 == 123.0 is True'

In [78]:
print("Comparing the two variables leads to the result:", a, "==", b, "is", equal)

Comparing the two variables leads to the result: 123 == 123.0 is True


***
## Proposed Solutions

(1.) Assign to two different variables the values ```123``` and ```123.0```.

In [79]:
my_int = 123
my_float = 123.0

(2.) Check with ```==``` whether these two variables are equal and save the result
to a new variable.

In [80]:
my_result = 123 == 123.0

(3.) Print the following sentences using strings, the two variables from (1.) and 
the boolean (result) variable from (2.) to output the following sentences:

``` Comparing the two variables leads to the result: 123 == 123.0 is True```

In [81]:
print('Comparing the two variables leads to the result:', my_int, '==', my_float, 'is', my_result)

Comparing the two variables leads to the result: 123 == 123.0 is True
